# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Release to Production to Azure Web App 

on:
  push:
    branches:
      - main
  
env:
  WEBAPP_NAME: java5git
  RESOURCE_GROUP: azuremigrateGarlan
    
      publish-profile:${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  release_to_prod:
    runs-on: ubuntu-latest
    needs: build
       
    steps:
      - name: Az login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Swap slots
        run: az webapp deployment slot swap -s staging -n java5git -g azuremigrateGarlan

  delete-slot:
    runs-on: ubuntu-latest
    needs: release_to_prod  
    
    steps:
    
      - name: Delete slot on staging site
        run: az webapp deployment slot delete --resource-group azuremigrateGarlan  --name java5git --slot staging

      - name: Close Pull
        uses: peter-evans/close-pull@v2
        with:
          pull-request-number: $(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          comment: Auto-closing pull request
          delete-branch: true
          
          
    
