# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - staging - PR - tjavagit1

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  WEBAPP_NAME: java5git
  SLOT_NAME: staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
       
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tjavagit1'
          slot-name: 'staging'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_STAGE_PUBLISHPROFILE }}
          package: '*.jar'
               
      - name: Post result to PR
        uses: mshick/add-pr-comment@v1
        with:
          message:  Preview link https://${{ env.WEBAPP_NAME }}-${{env.SLOT_NAME }}.azurewebsites.net
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
